# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_dag.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semantic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('edited_date', models.DateTimeField(blank=True, null=True, verbose_name='date edited')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django_dag.models.NodeBase),
        ),
        migrations.CreateModel(
            name='SemanticEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_date', models.DateTimeField(blank=True, null=True, verbose_name='date edited')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Semantic_parent', to='semantic.Semantic')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Semantic_child', to='semantic.Semantic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='semantic',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='_parents', through='semantic.SemanticEdge', to='semantic.Semantic'),
        ),
    ]
