# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semantic',
            name='edited_date',
        ),
        migrations.RemoveField(
            model_name='semanticedge',
            name='edited_date',
        ),
        migrations.AddField(
            model_name='semantic',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default='2016-05-02 22:20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semanticedge',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default='2016-05-02 22:20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semantic',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='semanticedge',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
