# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0002_auto_20160227_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='semantic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
