# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0003_semantic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semantic',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_parents', through='semantic.SemanticEdge', to='semantic.Semantic'),
        ),
    ]
