# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-18 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0004_auto_20160302_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticedge',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
