# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('edited_date', models.DateTimeField(blank=True, null=True, verbose_name='date edited')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'created_date',
            },
        ),
    ]
