# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_auto_20160227_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
