# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 10:03
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import semantic_cms.image_tools


class Migration(migrations.Migration):

    dependencies = [
        ('semantic_admin', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=semantic_cms.image_tools.upload_to_id_image),
        ),
    ]
