# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic_admin', '0003_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(blank=True, max_length=20, null=True)),
                ('blog_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
