# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160227_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
